POST http://localhost:3333/publication/create/4 
Content-type: application/json

{
    "title": "Olha que legal esse legal",
    "desc": "Esse cubo é muito raro muito raro mesmo"
}
###
PUT http://localhost:3333/publication/update/1
Content-type: application/json

{
    "title": "123123",
    "desc": "teste123"
}
###
POST http://localhost:3333/cubes/create/1
Content-Type: application/json

{
    "name": "Skewb",
    "rarity": "Pouco Comum"
}